spring:
  ai:
    mcp:
      server:
        name: ywy-image-search-mcp-server
        version: 0.0.1
        type: SYNC

        stdio: true

  main:
    web-application-type: none
    banner-mode: off
